'use client';

import React, { useState, useCallback, useEffect } from 'react';
import { 
  ArrowPathIcon, 
  CheckCircleIcon, 
  XCircleIcon,
  DocumentMagnifyingGlassIcon,
  DocumentArrowDownIcon,
  ClockIcon,
  ExclamationCircleIcon
} from '@heroicons/react/24/outline';
import { CheckCircleIcon as CheckCircleIconSolid } from '@heroicons/react/24/solid';
import { FunctionCardProps } from './types';
import { useSession } from 'next-auth/react';
import { saveAs } from 'file-saver';
import * as XLSX from 'xlsx';

interface ProjectSyncCardProps extends FunctionCardProps {}

interface ProgressStep {
  id: string;
  label: string;
  status: 'pending' | 'running' | 'completed' | 'error';
  detail?: string;
}

export default function ProjectSyncCard({ disabled = false }: ProjectSyncCardProps) {
  const { data: sessionData } = useSession();
  const [isRunning, setIsRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [currentTenantId, setCurrentTenantId] = useState<string>('');
  const [validationStats, setValidationStats] = useState<any>(null);
  const [validationData, setValidationData] = useState<any>(null);
  const [progressSteps, setProgressSteps] = useState<ProgressStep[]>([]);
  const [showProgress, setShowProgress] = useState(false);

  const fetchTenantInfo = useCallback(async () => {
    try {
      const response = await fetch('/api/tenants');
      if (response.ok) {
        const tenantData = await response.json();
        const currentTenant = tenantData.availableTenants?.find(
          (t: any) => t.tenantId === tenantData.selectedTenant
        );
        return {
          tenantName: currentTenant?.tenantName || 'Unknown Organisation',
          tenantId: tenantData.selectedTenant || 'unknown',
        };
      }
    } catch (error) {
      console.error('Failed to fetch tenant info:', error);
    }
    return { tenantName: 'Unknown Organisation', tenantId: 'unknown' };
  }, []);

  useEffect(() => {
    // Fetch tenant ID on mount
    fetchTenantInfo().then(info => {
      setCurrentTenantId(info.tenantId);
    });
  }, [fetchTenantInfo]);

  const updateProgress = (stepId: string, status: 'running' | 'completed' | 'error', detail?: string) => {
    setProgressSteps(prev => prev.map(step => 
      step.id === stepId ? { ...step, status, detail } : step
    ));
  };

  const handleProjectSync = useCallback(async () => {
    setIsRunning(true);
    setError(null);
    setValidationStats(null);
    setValidationData(null);
    setShowProgress(true);
    
    // Initialize progress steps
    const steps: ProgressStep[] = [
      { id: 'fetch', label: 'Fetching won deals from Pipedrive', status: 'pending' },
      { id: 'validate', label: 'Validating deals and Xero quotes', status: 'pending' },
      { id: 'analyze', label: 'Analyzing sync status', status: 'pending' },
      { id: 'report', label: 'Generating report', status: 'pending' }
    ];
    setProgressSteps(steps);
    
    try {
      // Use EventSource for real-time progress updates
      const eventSource = new EventSource('/api/sync/validate-stream');
      
      eventSource.onmessage = (event) => {
        const data = JSON.parse(event.data);
        
        switch (data.type) {
          case 'progress':
            updateProgress(data.step, data.status, data.detail);
            break;
            
          case 'log':
            console.log('Server:', data.message);
            break;
            
          case 'error':
            setError(data.message || 'Sync failed');
            eventSource.close();
            setIsRunning(false);
            break;
            
          case 'complete':
            // Set validation stats for display
            if (data.data.validationStats) {
              setValidationStats(data.data.validationStats);
              setValidationData(data.data);
            }
            eventSource.close();
            setIsRunning(false);
            break;
        }
      };
      
      eventSource.onerror = (error) => {
        console.error('EventSource error:', error);
        setError('Connection to server lost');
        eventSource.close();
        setIsRunning(false);
        
        // Update current running step to error
        const runningStep = progressSteps.find(s => s.status === 'running');
        if (runningStep) {
          updateProgress(runningStep.id, 'error', 'Connection lost');
        }
      };
      
    } catch (error) {
      console.error('Error running sync:', error);
      setError('Failed to start sync');
      setIsRunning(false);
    }
  }, [progressSteps]);

  const handleDownloadReport = useCallback(() => {
    if (!validationData) return;

    const workbook = XLSX.utils.book_new();
    
    // Summary Sheet
    const summaryData = [
      ['Project Sync Validation Report'],
      [''],
      ['Generated By', sessionData?.user?.name || sessionData?.user?.email || 'Unknown'],
      ['Generated At', new Date().toLocaleString()],
      [''],
      ['Summary Statistics'],
      ['Total Won Deals', validationData.validationStats.totalDeals],
      ['Fully Synced', validationData.validationStats.fullySynced],
      ['With Errors', validationData.validationStats.withErrors],
      ['With Warnings', validationData.validationStats.withWarnings],
      ['Fixable Issues', validationData.validationStats.fixableIssues],
      [''],
      ['Financial Summary'],
      ['Total Deal Value', `$${validationData.validationStats.dealsTotal?.toLocaleString() || 0}`],
      ['Total Accepted Quotes', `$${validationData.validationStats.acceptedQuotesTotal?.toLocaleString() || 0}`],
      ['Totals Match', validationData.validationStats.totalsMismatch ? 'NO' : 'YES'],
      [''],
      ['Top Issues']
    ];
    
    // Add top issues to summary
    if (validationData.validationStats.issueBreakdown) {
      Object.entries(validationData.validationStats.issueBreakdown)
        .sort(([,a], [,b]) => (b as number) - (a as number))
        .slice(0, 10)
        .forEach(([code, count]) => {
          summaryData.push([code, count]);
        });
    }
    
    const summarySheet = XLSX.utils.aoa_to_sheet(summaryData);
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');
    
    // Detailed Deals Sheet
    const dealsData = [
      ['Deal Details with Validation'],
      [''],
      ['Deal Title', 'Organization', 'Value', 'Currency', 'Xero Quote #', 'Quote Status', 'Quote Total', 'Products Total', 'Error Count', 'Warning Count', 'Issues']
    ];
    
    validationData.deals.forEach((deal: any) => {
      const issuesList = deal.validationIssues?.map((issue: any) => 
        `[${issue.severity.toUpperCase()}] ${issue.message}`
      ).join('; ') || '';
      
      dealsData.push([
        deal.title,
        deal.org_name || '',
        deal.value,
        deal.currency,
        deal.xeroQuoteNumber || 'Missing',
        deal.xeroQuoteStatus || 'N/A',
        deal.xeroQuoteTotal || 0,
        deal.productsTotal || 0,
        deal.errorCount || 0,
        deal.warningCount || 0,
        issuesList
      ]);
    });
    
    const dealsSheet = XLSX.utils.aoa_to_sheet(dealsData);
    XLSX.utils.book_append_sheet(workbook, dealsSheet, 'Deal Details');
    
    // Detailed Issues Sheet
    const issuesData = [
      ['Detailed Validation Issues'],
      [''],
      ['Deal Title', 'Issue Code', 'Severity', 'Message', 'Field', 'Current Value', 'Expected Value', 'Fixable', 'Fix Action']
    ];
    
    validationData.deals
      .filter((deal: any) => deal.validationIssues && deal.validationIssues.length > 0)
      .forEach((deal: any) => {
        deal.validationIssues.forEach((issue: any) => {
          issuesData.push([
            deal.title,
            issue.code || '',
            issue.severity || '',
            issue.message || '',
            issue.field || '',
            issue.currentValue !== undefined ? String(issue.currentValue) : '',
            issue.expectedValue !== undefined ? String(issue.expectedValue) : '',
            issue.fixable ? 'Yes' : 'No',
            issue.fixAction || ''
          ]);
        });
      });
    
    const issuesSheet = XLSX.utils.aoa_to_sheet(issuesData);
    XLSX.utils.book_append_sheet(workbook, issuesSheet, 'Detailed Issues');
    
    // Fixable Issues Sheet
    const fixableData = [
      ['Auto-Fixable Issues'],
      [''],
      ['Deal Title', 'Issue Code', 'Message', 'Fix Action']
    ];
    
    validationData.deals.forEach((deal: any) => {
      if (deal.validationIssues) {
        deal.validationIssues
          .filter((issue: any) => issue.fixable)
          .forEach((issue: any) => {
            fixableData.push([
              deal.title,
              issue.code || '',
              issue.message || '',
              issue.fixAction || ''
            ]);
          });
      }
    });
    
    const fixableSheet = XLSX.utils.aoa_to_sheet(fixableData);
    XLSX.utils.book_append_sheet(workbook, fixableSheet, 'Fixable Issues');
    
    // Generate and download file
    const wbout = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
    const blob = new Blob([wbout], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
    saveAs(blob, `project-sync-validation-${timestamp}.xlsx`);
  }, [validationData, sessionData]);

  // Only show for BSENI tenant
  if (currentTenantId !== '6dd39ea4-e6a6-4993-a37a-21482ccf8d22') {
    return null;
  }

  return (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow duration-200">
      <div className="p-6">
        {/* Header */}
        <div className="flex items-center justify-between mb-4">
          <div>
            <h2 className="text-xl font-semibold text-gray-900">Project Sync Validation</h2>
            <p className="text-sm text-gray-500 mt-1">
              Validate Pipedrive deals against Xero quotes
            </p>
          </div>
          <div className="p-2 bg-gray-100 rounded-lg">
            <DocumentMagnifyingGlassIcon className="h-6 w-6 text-gray-600" />
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="mb-4 bg-red-50 border border-red-200 rounded-lg p-3">
            <div className="flex items-center">
              <XCircleIcon className="h-5 w-5 text-red-600 mr-2" />
              <span className="text-sm text-red-700">{error}</span>
            </div>
          </div>
        )}

        {/* Progress Steps */}
        {showProgress && progressSteps.length > 0 && (
          <div className="mb-4 bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h3 className="text-sm font-semibold text-blue-900 mb-3 flex items-center">
              <DocumentMagnifyingGlassIcon className="h-4 w-4 mr-2" />
              Validation Progress
            </h3>
            <div className="space-y-2">
              {progressSteps.map((step) => (
                <div key={step.id} className="flex items-start">
                  <div className="flex-shrink-0 mt-0.5">
                    {step.status === 'completed' && (
                      <CheckCircleIconSolid className="h-5 w-5 text-green-500" />
                    )}
                    {step.status === 'running' && (
                      <div className="relative">
                        <div className="h-5 w-5 rounded-full border-2 border-blue-200 border-t-blue-500 animate-spin" />
                      </div>
                    )}
                    {step.status === 'error' && (
                      <ExclamationCircleIcon className="h-5 w-5 text-red-500" />
                    )}
                    {step.status === 'pending' && (
                      <div className="h-5 w-5 rounded-full border-2 border-gray-300" />
                    )}
                  </div>
                  <div className="ml-3 flex-1">
                    <p className={`text-sm ${
                      step.status === 'completed' ? 'text-gray-900' : 
                      step.status === 'running' ? 'text-blue-700 font-medium' : 
                      step.status === 'error' ? 'text-red-700' : 
                      'text-gray-500'
                    }`}>
                      {step.label}
                    </p>
                    {step.detail && (
                      <p className="text-xs text-gray-500 mt-0.5">{step.detail}</p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Validation Stats */}
        {validationStats && (
          <div className="mb-4 bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h3 className="text-sm font-semibold text-blue-900 mb-3">Validation Results</h3>
            
            <div className="grid grid-cols-2 gap-3 mb-3">
              <div className="bg-white rounded-lg p-3">
                <div className="text-2xl font-bold text-gray-900">{validationStats.totalDeals}</div>
                <div className="text-xs text-gray-600">Total Won Deals</div>
              </div>
              <div className="bg-white rounded-lg p-3">
                <div className="text-2xl font-bold text-green-600">{validationStats.fullySynced}</div>
                <div className="text-xs text-gray-600">Fully Synced</div>
              </div>
            </div>

            {validationStats.withErrors > 0 && (
              <div className="bg-red-50 border border-red-200 rounded-lg p-3">
                <div className="text-sm font-medium text-red-800 mb-2">
                  {validationStats.withErrors} Deals with Errors
                </div>
                {validationStats.issueBreakdown && (
                  <div className="space-y-1 text-xs text-red-700">
                    {Object.entries(validationStats.issueBreakdown)
                      .sort(([,a], [,b]) => (b as number) - (a as number))
                      .slice(0, 5)
                      .map(([code, count]) => (
                        <div key={code}>• {count} {code.toLowerCase().replace(/_/g, ' ')}</div>
                      ))
                    }
                  </div>
                )}
              </div>
            )}
            
            {validationStats.withWarnings > 0 && (
              <div className="mt-3 bg-amber-50 border border-amber-200 rounded-lg p-3">
                <div className="text-sm font-medium text-amber-800">
                  {validationStats.withWarnings} Deals with Warnings
                </div>
              </div>
            )}
            
            {validationStats.fixableIssues > 0 && (
              <div className="mt-3 bg-green-50 border border-green-200 rounded-lg p-3">
                <div className="text-sm font-medium text-green-800">
                  {validationStats.fixableIssues} Issues Can Be Auto-Fixed
                </div>
              </div>
            )}
            
            {validationStats.totalsMismatch && (
              <div className="mt-3 bg-purple-50 border border-purple-200 rounded-lg p-3">
                <div className="text-sm font-medium text-purple-800 mb-1">
                  Category Totals Mismatch
                </div>
                <div className="text-xs text-purple-700">
                  <div>Deals Total: ${validationStats.dealsTotal?.toLocaleString()}</div>
                  <div>Accepted Quotes: ${validationStats.acceptedQuotesTotal?.toLocaleString()}</div>
                </div>
              </div>
            )}
          </div>
        )}

        {/* Action Buttons */}
        <div className="space-y-3">
          <button
            onClick={handleProjectSync}
            disabled={disabled || isRunning}
            className="w-full inline-flex items-center justify-center px-4 py-3 text-sm font-medium text-white rounded-lg focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 disabled:opacity-50 disabled:cursor-not-allowed transition-colors duration-200"
            style={{
              backgroundColor: (disabled || isRunning) 
                ? 'oklch(21.6% 0.006 56.043)' 
                : 'oklch(27.4% 0.006 286.033)'
            }}
            onMouseEnter={(e) => {
              if (!disabled && !isRunning) {
                e.currentTarget.style.backgroundColor = 'oklch(21.6% 0.006 56.043)';
              }
            }}
            onMouseLeave={(e) => {
              if (!disabled && !isRunning) {
                e.currentTarget.style.backgroundColor = 'oklch(27.4% 0.006 286.033)';
              }
            }}
          >
          {isRunning ? (
            <>
              <ArrowPathIcon className="h-5 w-5 mr-2 animate-spin" />
              Validating Projects...
            </>
          ) : (
            <>
              <DocumentMagnifyingGlassIcon className="h-5 w-5 mr-2" />
              Validate Project Sync
            </>
          )}
          </button>

          {/* Download Button - Show only when validation is complete */}
          {validationData && !isRunning && (
            <button
              onClick={handleDownloadReport}
              className="w-full inline-flex items-center justify-center px-4 py-3 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 transition-colors duration-200"
            >
              <DocumentArrowDownIcon className="h-4 w-4 mr-2" />
              Download Validation Report
            </button>
          )}
        </div>

        {/* Info Text */}
        <p className="text-xs text-gray-500 text-center mt-3">
          Checks Pipedrive deals for Xero quote integration
        </p>
      </div>
    </div>
  );
}